server:
  port: 8222

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: bins-monitor-service
              uri: lb://BINS-MONITOR-SERVICE
              predicates:
                - Path=/api/v1/bin/**
